---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantuml-server
  labels:
    app.kubernetes.io/name: plantuml-server   
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plantuml-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plantuml-server
    spec:
      containers:
      - name: plantuml-server
        image: plantuml/plantuml-server:jetty
        ports:
        - name: http
          containerPort: 8080                                      
---
kind: Service
apiVersion: v1
metadata:
  name: plantuml
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer